# Generated by Django 2.2.4 on 2019-09-01 05:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190830_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100),
        ),
    ]
