# Generated by Django 2.2.4 on 2019-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190901_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='end_date',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password00', max_length=20),
            preserve_default=False,
        ),
    ]
