# Generated by Django 2.2.4 on 2019-09-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190901_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IC_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
