# Generated by Django 2.2.4 on 2019-09-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190901_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
