# Generated by Django 2.2.4 on 2019-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
