# Generated by Django 2.2.4 on 2019-09-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_registration_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='event',
            new_name='key',
        ),
    ]
