# Generated by Django 2.2.4 on 2019-09-04 05:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20190903_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='tagged',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
